name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - rc

env:
  FORCE_COLOR: 1
  PRE_COMMIT_COLOR: "always"  # https://github.com/pre-commit/pre-commit/issues/2918

jobs:
  Nox:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: wntrblm/nox@main
      - run: nox
